<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMEd8XKR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMEd8XKR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMEd8XKR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMEd8XKR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMEd8XKR\App_KernelDevDebugContainer([
    'container.build_hash' => 'MEd8XKR',
    'container.build_id' => '892a1449',
    'container.build_time' => 1611325356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMEd8XKR');
