<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'ot_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/Admin']], [], []],
    'ot_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'ot_tour' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::tour'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Tour']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'ot_admin_addtour' => [[], ['_controller' => 'App\\Controller\\TourController::addTour'], [], [['text', '/Admin/AddTour']], [], []],
    'ot_admin_createtour' => [[], ['_controller' => 'App\\Controller\\TourController::createTour'], [], [['text', '/Admin/CreateTour']], [], []],
    'ot_admin_edittour' => [['id'], ['_controller' => 'App\\Controller\\TourController::editTour'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/EditTour']], [], []],
    'ot_admin_updatetour' => [['id'], ['_controller' => 'App\\Controller\\TourController::updateTour'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/UpdateTour']], [], []],
    'ot_admin_tourcategories' => [['id'], ['_controller' => 'App\\Controller\\TourController::tourCategories'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/TourCategories']], [], []],
    'ot_admin_toursells' => [['id'], ['_controller' => 'App\\Controller\\TourController::tourSells'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/TourSells']], [], []],
    'ot_admin_tourselladd' => [['id'], ['_controller' => 'App\\Controller\\TourController::tourSellAdd'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/TourSellAdd']], [], []],
    'ot_admin_touritinerary' => [['id'], ['_controller' => 'App\\Controller\\TourController::tourItinerary'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/TourItinerary']], [], []],
    'ot_admin_tourfeatures' => [['id'], ['_controller' => 'App\\Controller\\TourController::tourFeatures'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/TourFeatures']], [], []],
];
