<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors~app.css',
                '/build/app.css',
            ],
        ],
        'tourcategories' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary~toursells.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary.js',
                '/build/tourcategories.js',
            ],
        ],
        'tourfeatures' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary~toursells.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary.js',
                '/build/tourfeatures.js',
            ],
        ],
        'toursells' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary~toursells.js',
                '/build/toursells.js',
            ],
        ],
        'touritinerary' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary~toursells.js',
                '/build/vendors~tourcategories~tourfeatures~touritinerary.js',
                '/build/touritinerary.js',
            ],
        ],
    ],
],

]];
